### ISSUE TITLE
[discussion] why should mods be loaded directly from the mods folder and why not

### ISSUE THREAD

**Issue by mandar1jn** [hk-modding/api#66]

**Comment by Ruttie2006** [comment]
Way easier, and there is no reason for a pointless folder in between.

**Comment by mandar1jn** [comment]
Another weird thing: why load from one sub folder but not sub folders of those folders? Like: let’s say there is a imaginary mod pack. It has a folder with the name of the mod pack and in that a seperate folder for each mod with a readme and all. That wouldn’t work

**Comment by valignatev** [comment]
A general rule of thumb is "flat is better than nested". Maintaining data structures and procedures that work with flat file systems is exponentially simpler than working with nested ones. Your case with a mod pack could easily be resolved with a file per mod in a single directory without subfolders, and a single README file that has each individual mod readme merged into it. It's a minuscule work for an imaginary mod pack maintainer, but it's an infinite ease of maintenance for modding API developers.

**Comment by fifty-six** [comment]
Besides the ease of maintenance for the API, it makes handling unmanaged dlls significantly simpler if you don't load subfolders. You can then keep them within the subfolders and load them yourself with a `[DllImport(...)]`, avoiding the exception from the c# assembly loader, the main example I've seen being DiscordRPC breaking the loader. As far as the direct loading from the folder goes, it is much simpler to support *only* folders as it avoids allowing people to get in the habit of throwing dlls in their mods folder and is also just less logic. The folders themselves are better as they allow for much easier management by automated utilities, bypassing the need for more complex file management and avoiding conflicts in storing special files like `README`s and `LICENSE`s which would otherwise be special-cased. Beyond this, it makes the detection of manual file management easier as if the folder is missing when not interacted with by a tool, then it can be assumed that the mod was uninstalled by hand. The 'cost' of folders on the part of mod developers is very little in that you can simply change something like your postbuild from
```xml
    <Target Name="CopyMod" AfterTargets="PostBuildEvent">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="D:/Steam/steamapps/common/Hollow Knight/hollow_knight_Data/Managed/Mods" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="D:/Steam/steamapps/common/Hollow Knight/hollow_knight_Data/Managed/Mods" SkipUnchangedFiles="true" />
    </Target>
```
to
```xml
    <Target Name="CopyMod" AfterTargets="PostBuildEvent">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="D:/Steam/steamapps/common/Hollow Knight/hollow_knight_Data/Managed/Mods/$(TargetName)" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="D:/Steam/steamapps/common/Hollow Knight/hollow_knight_Data/Managed/Mods/$(TargetName)" SkipUnchangedFiles="true" />
    </Target>
```
The only change being the addition of `/$(TargetName)` for the destination as the MSBuild task will create intermediaries as specified under DestinationFolder [here](https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task).
